# Generated by Django 4.2.5 on 2024-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', '老師'), ('student', '學生')], default='student', max_length=7),
        ),
    ]
