# Generated by Django 5.0.3 on 2024-03-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_week', models.IntegerField(choices=[(1, '每周一'), (2, '每周二'), (3, '每周三'), (4, '每周四'), (5, '每周五'), (6, '每周六'), (7, '每周日')])),
                ('time_period', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('lecturers', models.ManyToManyField(related_name='teach_courses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
